name: 'Slack Notification Action'
description: 'Envia notificações para o Slack sobre eventos do GitHub - Versão TypeScript'
author: 'Samuel Campos'

inputs:
  webhook-url:
    description: 'URL do webhook do Slack'
    required: true
  message:
    description: 'Mensagem personalizada (opcional)'
    required: false
    default: ''
  channel:
    description: 'Canal do Slack (opcional)'
    required: false
    default: ''
  username:
    description: 'Nome do bot (opcional)'
    required: false
    default: 'GitHub Action Bot'
  icon-emoji:
    description: 'Emoji do bot (opcional)'
    required: false
    default: ':rocket:'
  include-event-details:
    description: 'Incluir detalhes do evento (true/false)'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout Action Repository'
      uses: actions/checkout@v4
      with:
        repository: samuelBarreto/Action-Slack
        ref: main
        path: ./.action-repo
    
    - name: 'Setup Node.js'
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ./.action-repo/package-lock.json
    
    - name: 'Install dependencies'
      shell: bash
      working-directory: ./.action-repo
      run: npm install
    
    - name: 'Build TypeScript project'
      shell: bash
      working-directory: ./.action-repo
      run: npm run build
    
    - name: 'Run compiled test script'
      shell: bash
      working-directory: ./.action-repo
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook-url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_JOB_STATUS: ${{ job.status }}
        CUSTOM_MESSAGE: ${{ inputs.message }}
        SLACK_CHANNEL: ${{ inputs.channel }}
        SLACK_USERNAME: ${{ inputs.username }}
        SLACK_ICON_EMOJI: ${{ inputs.icon-emoji }}
        INCLUDE_EVENT_DETAILS: ${{ inputs.include-event-details }}
      run: node dist/test-local-fixed.js 