name: 'Test Action'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Test Basic Notification'
        uses: ./
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
      
      - name: 'Test Custom Message'
        uses: ./
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: '🧪 Teste da Action - Mensagem personalizada'
          channel: '#testes'
          username: 'Test Bot'
          icon-emoji: ':test_tube:'
      
      - name: 'Test Without Event Details'
        uses: ./
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          include-event-details: 'false' 